services:
  app:
    image: fxhibon/fresh-fridge:0.0.10
    container_name: fresh-fridge
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - proxy
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fresh-fridge.entrypoints=websecure"
      - "traefik.http.routers.fresh-fridge.rule=Host(`fresh-fridge.fxhibon.fr`)"
      - "traefik.http.routers.fresh-fridge.tls=true"
      - "traefik.http.routers.fresh-fridge.tls.certresolver=myresolver"
      - "traefik.http.services.fresh-fridge.loadbalancer.server.port=3000"
      - "traefik.http.routers.fresh-fridge.middlewares=global-ratelimit,crowdsec-bouncer"

  db:
    image: postgres:18-alpine
    container_name: fresh-fridge-db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/18/docker
    networks:
      - proxy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  backup:
    image: ghcr.io/solectrus/postgres-s3-backup:18
    container_name: fresh-fridge-backup
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    networks:
      - proxy
    env_file:
      - .env

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:v0.19.1
    container_name: fresh-fridge-postgres-exporter
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    networks:
      - proxy
    env_file:
      - .env
    environment:
      - DATA_SOURCE_NAME=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable

networks:
  proxy:
    external: true

