docker_username: ENC[AES256_GCM,data:xAkVR+KhAA==,iv:6KvIlzBUFr2LbjVQy3VaG+1nT9Eqw9FAhImDsqIJmfI=,tag:1da1edOn8bzoOjAFkx26XA==,type:str]
docker_password: ENC[AES256_GCM,data:T5Ib7AGgZprMOD5GM9PU21TzwjwOIT8/h7R5jRw0oMGkH/5j,iv:D7YnpHSdD/BIQORdG7XI2AipHVpyvYM8h/qB63gJ2y0=,tag:zUaXeVyT21VOPhLCmhigUA==,type:str]
fresh_fridge_gemini_api_key: ENC[AES256_GCM,data:1pwUY7UfwwWjW6yKG9FtdCz23GPR5ewjcOjUAdTd8uFEPouiRDRS,iv:y5EFKKS0T62Gff5P7Oqwnq0VGDC2weqG14VFMcIX2xg=,tag:Nxzl6kEGq7KJ9TFiemJJIw==,type:str]
fresh_fridge_postgres_user: ENC[AES256_GCM,data:hSZ48VaQqmBQQxI=,iv:608k9Gg0wqC1KaGzZ2oWZCMgdoycwnGT9Gx/t7iS0yk=,tag:uqdzdEkyOuhB/8Vt8GZeZw==,type:str]
fresh_fridge_postgres_password: ENC[AES256_GCM,data:O4Src5yIgoD5vIPYPRwN1Hyjj3iLjec82qw7s9+Tycs=,iv:GaMq8U3svOJhFc6/qtBP0dxJCD9hHFJi9R0m1aIkCxY=,tag:OF1sKxYeEdzM3LTkzwbpnQ==,type:str]
fresh_fridge_postgres_db: ENC[AES256_GCM,data:DRn+MurXAviNx7g=,iv:8SGy4GYcmYdSFRvozBoiVkY0ymg2DATwSwJLFTH3wJs=,tag:dlXYsh6rFxvDAnDZEJ6rbQ==,type:str]
transmission_vpn_username: ENC[AES256_GCM,data:CqaVoeAFR8K4Sdy3NorDZMjptZg=,iv:/lYQGHwT0HMhBz6+TV/rAv9HX9+V594BmOsb5S+tM7o=,tag:UQnlTTQxE5aeg1+ySVrGSw==,type:str]
transmission_vpn_password: ENC[AES256_GCM,data:0sSQxcqioO1AXS2rMPSuZbpKHlzyzvTHqkyRg0tOWWM=,iv:z5qPvDBRhR8dbSeKniBSnsBnGEkL7JvRatBMJgibg0g=,tag:OSZJHvcO1bBhyAiOTuQ7aA==,type:str]
plex_token: ENC[AES256_GCM,data:7eO63QQmrZixl2GIfAlpHUZPBqg=,iv:TaPvO4+P47EcJsBhS1DWVp2OLhLPWZdWTYzI3IkivhY=,tag:15KsHGX5zW8SguA3oqBkvQ==,type:str]
rp5_grafana_admin_password: ENC[AES256_GCM,data:qWH0Z6PFe5e1gbxQ6E2GHj2T6QjPM/uCbK1n4lc+CW9YIur88F4nhHRuKlsl,iv:2m6LcP+d0eA3BsUOv9DGyOfg6q42RjeStFlcJ5aMNrE=,tag:1Uip7ZoL99j74kIBZ7+erA==,type:str]
rp5_telegram_bot_token: ENC[AES256_GCM,data:i/59KdbKq5vTIuoLOm04IJKxju7QNyQJb0SCYl97WH6JMmWxCT4AJFGd3prpsg==,iv:2i+s22m0DYEgEd/ORkWW+ML8dy9MYkYYsJD95in9AdU=,tag:BiukWHL7XQeHLj2JvuRLIg==,type:str]
rp5_telegram_chat_id: ENC[AES256_GCM,data:qbQVeZK+uU0v,iv:ZK984byjXzxo07vlLEQe5J+cCG3PcJY2bAHyI27r1Ns=,tag:lpqGlw3FZDdpOwE69I/ykw==,type:int]
fresh_fridge_s3_access_key_id: ENC[AES256_GCM,data:1SUZSRGCOTbSg59oLhCKx2O1dhpXaOR04uheD04aM8s=,iv:STNzZdDEIKj3u//GexsQiNcA88Wr+X1m1QpGUgSF1lc=,tag:kG4+FlfRPaDY7hfg45lumQ==,type:str]
fresh_fridge_s3_secret_access_key: ENC[AES256_GCM,data:QQwbl0T6peVe6txLp6vyO30vgEpsbwLzaTlU/Gkqpl8=,iv:DU+kOmILSb1IinvMadZonlb/+rQIZh82rPopMMn+6os=,tag:WQ/60lEoVF+V/Mee7B5rDw==,type:str]
vps_grafana_admin_password: ENC[AES256_GCM,data:mEKZ+ITSIrToAdlVDPCcW7vJ0wIgb6ZnrEzmiektPEQ=,iv:eL9LKV1gUvsrdkAPN0rUF6hIm1IDMqHXyobslCND+Ek=,tag:bR0F2miLpsYX2CTgIUiJHw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0UWRYKzYrRjFzQ3pORGUx
            NE45VlNtV0h6ZXNPQWhGSVBwaVV2N2tUNVJnCmtZOXdLZFhtb1JhS0trNFBQTHpw
            aC84TGZSZHIzU3pyTVR1V2xzZHpLZ00KLS0tIGxKOXJ4Y2NWdjNQeGVzMmRRSVZl
            bm0rWWdzeVM5M2gvS2xra0JPcHlleGsKaloWC0rFK+5GmkLK9gMyFx3CJ9foUKRL
            bpJVwOaNB0+zbQbN+jONu9kvpJ9/WXx7K3vu9KSiYaCkVykiWT4+0w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1clehw5qfnjcx8dc45hr0zldvrw37fhp6xvfyf5fgxxkvde58ccjs7kmcgq
    lastmodified: "2026-06-05T21:51:28Z"
    mac: ENC[AES256_GCM,data:IPjfk5UmV+2gy/9s2eWPt7RkNef8web0Nbnhk3PahkuQMrTRq7suw19Bq/yhOTcdVe0MHRrXNnanpZY3NBbsC5y9Wm4N3HAKFTdbtCTi17PagrPsLgXijaRSq97hVbpNmOH8oyGFdQiEG3VTGpBnc6Cmpq/YIsrhBB0Vr6duGD4=,iv:00zl4WgOZ8rlSFA+CYg7jjZENHrusPunlfvmiyzDL1Y=,tag:3vcq9nco6LKxQiJmbAzubw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
