docker_username: ENC[AES256_GCM,data:IwAS3JTkXA==,iv:++vpOCBZ2oQiSRKB/Gln6QP3RQrUfB/N4fsX9S9Hmi8=,tag:heXtkt2oPZGnPaEJBXN8CQ==,type:str]
docker_password: ENC[AES256_GCM,data:OHD8kccIFJiJ37ctHYcatkDjeye5Y2iFaK7Eb9N5M5VvuulP,iv:k2mHnb4q7pk/YEFaHooTa8mC78tmjiTVPlTKxJTvXwc=,tag:eDIoO3WQ0knl2jfkA6Gd3g==,type:str]
fresh_fridge_gemini_api_key: ENC[AES256_GCM,data:GFNA+AEF4qQb20d6yYRK5qJ/XcZVE3eJhzYucFESBP/VldGNOVeF,iv:IibQRnwb7uOVihINmvD8ubDPIJWgErrJ7iC69Wurgjs=,tag:/g0ShriLxAH8NSZS87pD4w==,type:str]
fresh_fridge_postgres_user: ENC[AES256_GCM,data:qkGkPgIwXWs+8JM=,iv:KU67M6O66QmZ5VfLlxKmnCKW4P/tQEUldyHoQGfHWCA=,tag:CeG0PADslReKYnb2c2O//w==,type:str]
fresh_fridge_postgres_password: ENC[AES256_GCM,data:vsaItM+YRrTh7d34xPVSNlrgy4+gD67JFCcxZHYh/KQ=,iv:8k+Y04Nym/tL/6GymtutwQToP151UFX4M4cns+tBprI=,tag:NL+JHIjMQze3de7paJOeqw==,type:str]
fresh_fridge_postgres_db: ENC[AES256_GCM,data:2fY8UUFhABP2EQ8=,iv:S0AlqTSouHctfKXsmHAqIOJOHOfiGGe2wZm7nqREP3E=,tag:VEyjQx4h/j4+kNh3JTFWng==,type:str]
transmission_vpn_username: ENC[AES256_GCM,data:mXQBTNMfVMPhs6XZhB286dHFXBo=,iv:BpEsHR//+X4YrjXrCQgYVZRC4Tr3rmt9oQaHKVcAqr8=,tag:N61ju+dzU2ARLDrOp1VQ7A==,type:str]
transmission_vpn_password: ENC[AES256_GCM,data:Hvktsy7nStaqLrYA3pYMza9bNRP5BD282m06aP4y95Q=,iv:VRewWg7HD4lZGqDqQ6EzaJPyOd5w2IqCpbnsGKaM5fY=,tag:C1+sTAoBbGeAp/+U5h4cSQ==,type:str]
plex_token: ENC[AES256_GCM,data:YJCV/p6BJYim2zX1G4H3iH6tGH0=,iv:KxsBn8Y9GyA2k12QqHQaeR1aKZbdVntdsD0bmaJunP0=,tag:hK0FiX10vo53rHIt6rvIgQ==,type:str]
rp5_grafana_admin_password: ENC[AES256_GCM,data:sYqAGGYWOn54RnDyjNbtTO91P5+Q3nqxAWSeOgd8uHlIcgyiOTXl2HmyaVqH,iv:l4GzSGVs6r0i7Akx6l0N2wdFW1UgoBRlaQq6A3AQd8o=,tag:6ZbreNxWgNqueRMxww6i3A==,type:str]
rp5_telegram_bot_token: ENC[AES256_GCM,data:XDUhFPI5EeMok2dRnTEpuwUQR5NbQjUhgJlBMBPp2Ko/xc2pHjzpklxlQYkujQ==,iv:18o3DpD2UuiFJyh7oXe/kCnhLzcIk6dA4AjUa8KDPUc=,tag:ifyWitXmnpydlYBjXjiYLA==,type:str]
rp5_telegram_chat_id: ENC[AES256_GCM,data:FvHbAICJVXOC,iv:iCLKVVVsRJwsvmYzAWTJxWDqHpqplyeJNnfokUNjBUU=,tag:MmbQq860c3UGbXU74H3e3w==,type:int]
fresh_fridge_s3_access_key_id: ENC[AES256_GCM,data:oVbqsUsEupcG3AUaLDgtRC8x1dhUzAEX5ppWGHRsr6o=,iv:9dCTgkhGVwIUHsbsQ+6ZQtDdmSUTlcQwndCfF9PeA6o=,tag:Cr1EPFYOImmKy8ozYW0LEw==,type:str]
fresh_fridge_s3_secret_access_key: ENC[AES256_GCM,data:GN/O7Scf9TqXPRmwPkBouzO4pGeN9nI4kAgjUdmyx34=,iv:mF37llFybks2AedNJIgb5w4dauNkgqKJMUDVqHnIINQ=,tag:Kns8KbHsVRmA4lYWPZX6IQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMFVockd5SGY3L1E2akZS
            Y0IvSW9VQUcvK25ueVJHRGRHbmk2UzBkTGhNCmtNdlU0ZW1mUFdwMnQ1ZndTWkJr
            UkRyNjZ2OFNRcUxRT2RVems2bXcyaGcKLS0tIHg0UHdlUVVQOTluQm1iamlxdkJx
            YTl0NHlpQldMejF1cFVyanZhZUlNQncKCaDjMdmLN331C/eeJnLZ3stbor/N7azh
            VZUyol669i+JEBLeFcT9vzgyiCKWVvQieYyiAryqJt2LaLEPASZtDw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1clehw5qfnjcx8dc45hr0zldvrw37fhp6xvfyf5fgxxkvde58ccjs7kmcgq
    lastmodified: "2026-06-05T18:47:50Z"
    mac: ENC[AES256_GCM,data:qvKCRR8855E4BEvc1g2Yu7R1frasngG/qoP3SL7mtvfxpAaZTZNCToLTxwCPPM1g0UEhugxPG8YX1JIYsuhgKpH1qJxN4NxkU6/4R5xWyVMwlWzkdao5eLpXsfNx5duqYvcuWf08JNSvbaWDj33RSamgTEXGj/fPTew6juwuldA=,iv:oElrB3SoYdf5eQRlkb5orlg0e3xndbTAJo4gsQ3Os60=,tag:5e93vDL78Y0VEQDFgvJ/Hg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
