#ENC[AES256_GCM,data:D8nIb+Ys2q0RISDUQou5frqjnG7n8sdAvl8YmoTxEA==,iv:CpPGiDbjIpudc6BpoKhfzReetUtl8fLVkuxF2rfpYg8=,tag:Gd+Tla2+gC57xZvwN359Uw==,type:comment]
backend:
    s3_access_key_id: ENC[AES256_GCM,data:iba0FrvlbGuvl8njC2+/2fqZgU7Cd65725A5rWTPkkk=,iv:g4QQBSCgKvnYoNnqXb6MF95Suw0aSsyJ5zQR18haF8k=,tag:OVgm2jb8egIFZ/sSaJiPzw==,type:str]
    s3_secret_access_key: ENC[AES256_GCM,data:R2QbG5zS0jpmdmGIlk5gN6GMOP+BHw55/77ECDehv84=,iv:SANo+4N7Ewk+cQXF0SNAXa0WHcJtuIIqc51SoIqA6fM=,tag:rqGcrSw7n3uQQsHQCZdx5g==,type:str]
ovh:
    application_key: ENC[AES256_GCM,data:WKZiPRay20y1kaz3B2Ekeg==,iv:krwRIuHpl0Vez0Yn+0+xFP4z234Kqx8OhGDMVd4vT+0=,tag:s/RJvTqzGpNdtSS54A9kPA==,type:str]
    application_secret: ENC[AES256_GCM,data:DqTDH0SKgU23wlnoDkAYe2TaCFYbRze/p6JZ3s4YGAI=,iv:zEJJdZ/sD2fEP+gFkUSKoub4LcUcpdXoijlfGLkDKTw=,tag:Js7seKhz4GHKvP6wXWfLcg==,type:str]
    consumer_key: ENC[AES256_GCM,data:9McKRHolTMa5kBwJfTkMmb9n5t5QN2T/ZON2UKGkBS8=,iv:gW+mJ2Tq2ExVt4r6DqioZA8g4qViTRu0mY+awRd9lwc=,tag:rf69sRXFsVu6Wxx2q5cMPg==,type:str]
    cloud_project_id: ENC[AES256_GCM,data:iyOEwwKnzQ6pPbzuXix6t3YfggzT+D75gnmnQGIzfqY=,iv:YTuAeWcG4ZDhNY6va26xwUgdTTZsnr0jURjxPJy0kro=,tag:QyG3gDeNX1eI6KnEtt+EdA==,type:str]
home_ip_v4: ENC[AES256_GCM,data:CWteCzxd3Qw0hA==,iv:QPcrCweLhELn7fDcR6R9RUc9B5EjNcmw670YEAXESUk=,tag:25HFKirc4p3LTrXy+OEFXg==,type:str]
sops:
    age:
        - recipient: age1clehw5qfnjcx8dc45hr0zldvrw37fhp6xvfyf5fgxxkvde58ccjs7kmcgq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRM0szWXdJMUV2RlBPZGJa
            WXcxZUFlTTMxRG40VWVYeWZwVDYvZVdjMEQwCk93SXhIcjFvL3NJbit6cCtnNlJ0
            VXdNOEVLY3FBVkVxQ01kL1pLdk9XTk0KLS0tIDJLSHYxN1E5dEtaQkJjdk5BcFNC
            RXNvbmsxQ1YyQlc0ZHRFVzVOZHhhOUEKuxNKt+zwXgQsVNEnOoaRfGs5oVbumCPn
            /lUWNvGsI9rfd7pYb8oSblZqshxFV1Wy5NMQxxJjLaPz9Pka4mx/hA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-07T19:31:09Z"
    mac: ENC[AES256_GCM,data:dDth8RFzvFdJEHsCfaRQswaQu6/1Ju1OoFAHqYUQ0cxXglotFlHxfo7N2SuQcQ8Rdh3dl/hcENZYt9yYoqXXtoabSr+0FOo9yj8ie6A8QCeCcxLgKJ1s5NwqLZvyAf62ym6yY4v3DnGKX6tykPBHsH/FtOVHNBDfjzLfooJWokI=,iv:P5yNGz1jL9LYgzxGw2ZzEzG90+Se3NynZoiS7xLX9ic=,tag:XOflZXML8DJ2xsiXtCMo/A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
